### ISSUE TITLE
Implement C equivalent of sqlite3.Row

### ISSUE THREAD

**Issue by rogerbinns** [rogerbinns/apsw#137]
_From [rogerbinns](https://code.google.com/u/rogerbinns/) on December 21, 2012 10:48:09_

Basically produce a named tuple that can be used as a Row tracer.

_Original issue: http://code.google.com/p/apsw/issues/detail?id=137_

**Comment by lllama** [comment]
I know this is an old issue but is there a recommended way to get named column access to results?

**Comment by rogerbinns** [comment]
There is an example in the tips, making the result be a dictionary:

https://rogerbinns.github.io/apsw/tips.html#customizing-cursors

Do you have a preferred type for return other than a dictionary?  I am thinking of updating the doc to show returning [named tuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) or [dataclass](https://docs.python.org/3/library/dataclasses.html#module-dataclasses)

**Comment by lllama** [comment]
I'm currently creating dataclasses by doing `MyClass(*result)` so that would be my preference. 

(I'm actually using [aiosql](https://github.com/nackjicholson/aiosql) to call my queries, so I will have to see whether I can drill down to the cursor for that - but that's not important for this issue.)

**Comment by rogerbinns** [comment]
Shipped
