### ISSUE TITLE
Getting cursor description when the result is an empty list of rows

### ISSUE THREAD

**Issue by Thyfate** [rogerbinns/apsw#160]
Hi and thanks for APSW,

I would need to be able to determine the number of columns which a SQL select statement would return, even when the number of returned rows is empty. 

Calling cursor.description or cursor.getdescription() does not work because when the result is empty, I get the error "Can't get description for statements that have completed execution"

I would need this feature for a numerical application using numpy where the data returned from the db is directly translated into a numpy array. So that multidimensional calculations work I need to return a numpy matrix of (0 x the number of columns of the select statement) when the result is empty. I can do this with the standard library sqlite driver by using cursor.description but I could not find a way to do it with APSW. The only alternative I can think of would be to hard code the number of columns but that would be inviting bugs because any modif to the SQL statement would have to be reflected in the hard coded number of columns...

Please let me know if there is a way to access this information or if you could consider implementing this feature.

Thanks in advance

**Comment by lennax** [comment]
Sorry to revive such an old thread. I'm running into this problem while attempting to use pandas with apsw. I get this error from `pandas.read_sql_query(query, con)` if there are no result rows:

> File "[..]/pandas/io/sql.py", line 1495, in read_query
>     columns = [col_desc[0] for col_desc in cursor.description]
> apsw.ExecutionCompleteError: Can't get description for statements that have completed execution

My current workaround is to wrap the pandas query in a `try: ... except apsw.ExecutionCompleteError: return pandas.DataFrame()`. The execution tracer ignored my attempt to return `cursor.description` for a more precise empty result, but fortunately I just need to know that there are no rows. 

Overall, apsw works much better and more efficiently than pysqlite. Thanks for the great work.

**Comment by rogerbinns** [comment]
The pandas code is this:

        cursor = self.execute(*args)
        columns = [col_desc[0] for col_desc in cursor.description]

The problem is that the execute step can run to completion so there is no description, as you diagnosed.

It looks like the cursor having a method returning its current state would be helpful to you.  That way you would know if the execute ran to completion or is sitting on a result row.  DBAPI is silent on this.  Would an is_execution_complete() method on cursor work for you?

The method can be simulated by getting the description and ExecutionCompleteError telling you it is complete.

**Comment by lennax** [comment]
Regarding cursor status, the EAFP method is Pythonic and  working for me.

I have only user-level, not dev-level, knowledge of DBAPI or pysqlite, but I found that the pysqlite cursor provides column information for empty result sets:

    import sqlite3
    import pandas as pd
    sconn = sqlite3.Connection(":memory:")
    print pd.read_sql_query("SELECT 1 AS a LIMIT 0", sconn)
> Empty DataFrame
> Columns: [a]
> Index: []

**Comment by rogerbinns** [comment]
pysqlite saves the description for every query just before execution, and saves it on the cursor itself so that it is available even after execution has completed.  APSW only gets the description when you ask for it, and discards it after execution of a statement completes.

APSW only makes you pay for what you use, which is one reason it performs better.

**Comment by lennax** [comment]
Thanks for the explanation. It's a "sacrifice" I'm more than willing to pay for the performance of apsw.

**Comment by HarryPehkonen** [comment]
In my use-case, I don't care about .description if there are no hits, but I like building dictionaries.  Not sure if there's a better way:

    headings = []
    for hit in cursor:
        if headings == []:
          headings = [x[0] for x in cursor.description]

        d = dict(zip(headings, hit))

I think it would be nice to have an "is_execution_complete()" method, but only if it's efficient (wouldn't want to contaminate other use-cases).

**Comment by rogerbinns** [comment]
is_execution_complete in general doesn't make sense for SQLite.  In particular SQLite does the least amount of work when you ask for the next row, to return that row.  The only way to find out there is no next row, is to ask for it, let SQLite do the work, and it will then either return a row or say there is no more.  (Popular server databases instead generally tend to calculate the entire result set, before returning the first result row.)

Since you use the cursor as an iterator (best practise), execution is complete when the cursor stops iterating.  Simple as that.

**Comment by Xender** [comment]
Would you be willing to either add a new method to Cursor class to save the description up front, or a boolean keyword argument for `Cursor.execute()` or `Cursor` constructor (defaulting to False) that would facilitate that?

The snippet with manually setting the tracer is just too low-level to be convenient, and I think this thread indicates that there is in fact some need to have this as an option (still preserving more performant version as default).

**Comment by rogerbinns** [comment]
@Xender using the execution tracer is the solution.  The execution tracer can be set on a cursor, or the connection as a whole.  You can use a [connection_hook](https://rogerbinns.github.io/apsw/apsw.html#apsw.connection_hooks) to ensure connections are setup however you want them.

**Comment by jgwinner** [comment]
Sorry for the necro, but @HarryPehkonen Thank you for that code, I spent a bunch of time trying to figure out how to dump a SELECT statement into JSON.
