### ISSUE TITLE
APSW gives IOError after setting journal mode to WAL on NFS

### ISSUE THREAD

**Issue by wsong** [rogerbinns/apsw#173]
I'm aware that WAL mode doesn't work with networked file systems, but I'm seeing some unusual behavior while trying to work around this.  If I set the journal mode to WAL and then see an IOError, I'd like to switch the journal mode back to DELETE, but it often takes more than one try to set the journal mode back.  For instance:

```
>>> import apsw
>>> db = apsw.Connection('/foobar/test.db')
>>> c = db.cursor()
>>> c.execute("pragma journal_mode=WAL").fetchall()
[('wal',)]
>>> c.execute("create table x (data text)").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cursor.c", line 231, in resetcursor
apsw.IOError: IOError: disk I/O error
>>> c.execute("pragma journal_mode=DELETE").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cursor.c", line 231, in resetcursor
apsw.IOError: IOError: disk I/O error
>>> c.execute("pragma journal_mode=DELETE").fetchall()
[('delete',)]
>>> 
```

Why does the first journal_mode=DELETE call fail but the second one works?

**Comment by rogerbinns** [comment]
APSW does not alter SQLite's behaviour so this is not an APSW issue.

You can use the extended error code to work out what the IOError is about: http://rogerbinns.github.io/apsw/exceptions.html#exceptions

SQLite's diagnostics will also give you more information http://rogerbinns.github.io/apsw/tips.html#diagnostics

SQLite itself doesn't work on networked filesystems, because they mess up locking.  It may appear to work initially but you will eventually end up with problems.  https://www.sqlite.org/howtocorrupt.html 2.1
