### ISSUE TITLE
testextension is not built by default with MSVC

### ISSUE THREAD

**Issue by desb42** [rogerbinns/apsw#182]
In a Windows environment testextension does not get built automatically and when the test script test.py runs it suggests a compile using gcc.

The following two lines when run within an MSVC command shell will create this extension and allow test.py to run all its test

cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DNDEBUG=1 -D_CRT_SECURE_NO_WARNINGS=1 -I. -Isqlite3 /Tcsrc/testextension.c /Fotestextension.obj

link.exe /DLL /nologo /INCREMENTAL:NO /EXPORT:sqlite3_extension_init /EXPORT:alternate_sqlite3_extension_init testextension.obj /OUT:testextension.sqlext /IMPLIB:testextension.sqlext.lib /MANIFESTFILE:testextension.sqlext.manifest

**Comment by rogerbinns** [comment]
Everything is as intended. APSW knows how to [compile the test extension](https://github.com/rogerbinns/apsw/blob/master/setup.py#L117) and does so as part of the [building and testing](http://rogerbinns.github.io/apsw/build.html#testing) that is done.  In short the extension loading mechanism is tested on the various platforms.

The reason why the build command is not exposed, and the tests.py does not require the compiled extension is because the valid remaining tests are using a compilation environment different than that apsw/python use.  This is especially the case on Windows with a wide variety of compilers, serious versioning issues, a bewildering variety of flags etc.

So if you intend to use extension loading, compile extensions using your chosen compiler, version and flags.  Compile the test extension and run tests.py to verify it fundementally works.

Admittedly the tests message could be better, but I don't want to include several paragraphs.  The vast majority of people on Windows will be using the provided binaries (which have been tested) while those compiling for themselves will know what compilers and flags they want to use.
