### ISSUE TITLE
Shell `load_extension()` causes SQLError but `.load` does not

### ISSUE THREAD

**Issue by WindfallLabs** [rogerbinns/apsw#197]
I think I found a bug in the apsw shell. `SELECT load_extension('<extension>');` returns `SQLError: not authorized` until `.load <extension>` is used. Afterwards it works fine, although it's no longer needed.

**Comment by rogerbinns** [comment]
That is how SQLite works.  The [load extension api](https://www.sqlite.org/c3ref/load_extension.html) will fail until a [C api call to enable](https://www.sqlite.org/c3ref/enable_load_extension.html) is done.  The .load command [automatically does the call](https://github.com/rogerbinns/apsw/blob/master/tools/shell.py#L1922).  The load_extension SQL level function just calls [load extension](https://www.sqlite.org/c3ref/load_extension.html).

The only way APSW could work around this is by either parsing the SQL to work out all functions called and silently enabling, or provide an overloaded load_extension that does the enabling automatically.  Both are bad ideas, precisely for the reasons given for the enable mechanism in the first place (aka "security").

It is also worth pointing out that the APSW shell behaves exactly as the SQLite shell does.  If the behaviour is different then I will update to match, otherwise no changes.

**Comment by WindfallLabs** [comment]
Personally, I favor the `.load` way, but it does seem different.  
![sqlite_shell](https://cloud.githubusercontent.com/assets/10524780/11571378/370602b8-99b9-11e5-9fef-bdb8afcb93ab.PNG)

**Comment by rogerbinns** [comment]
You are right - apsw is not behaving the same way as SQLite shell, so I will fix this.  The code below is what the SQLIite shell does:

```
/*
** Make sure the database is open.  If it is not, then open it.  If
** the database fails to open, print an error message and exit.
*/
static void open_db(ShellState *p, int keepAlive){
  if( p->db==0 ){
    sqlite3_initialize();
    sqlite3_open(p->zDbFilename, &p->db);
    globalDb = p->db;
    if( p->db && sqlite3_errcode(p->db)==SQLITE_OK ){
      sqlite3_create_function(p->db, "shellstatic", 0, SQLITE_UTF8, 0,
          shellstaticFunc, 0, 0);
    }
    if( p->db==0 || SQLITE_OK!=sqlite3_errcode(p->db) ){
      fprintf(stderr,"Error: unable to open database \"%s\": %s\n", 
          p->zDbFilename, sqlite3_errmsg(p->db));
      if( keepAlive ) return;
      exit(1);
    }
#ifndef SQLITE_OMIT_LOAD_EXTENSION
    sqlite3_enable_load_extension(p->db, 1);
#endif
    sqlite3_create_function(p->db, "readfile", 1, SQLITE_UTF8, 0,
                            readfileFunc, 0, 0);
    sqlite3_create_function(p->db, "writefile", 2, SQLITE_UTF8, 0,
                            writefileFunc, 0, 0);
  }
}
```

**Comment by rogerbinns** [comment]
Looking at this again, the sqlite shell has a defensive mode and similar, which is a route I don't want to go down.  I want it to be safe to send large amounts of SQL at the apsw shell without having to worry about problems.  Consequently requiring the use of `.load` seems a reasonable compromise, since that indicates the shell is intentionally being used as a shell.
