### ISSUE TITLE
Documentation build should not fetch external files

### ISSUE THREAD

**Issue by Elizafox** [rogerbinns/apsw#198]
As per [Gentoo policy](https://devmanual.gentoo.org/ebuild-writing/functions/index.html), ebuilds cannot fetch external files. Other distributions also share this same policy. Unfortunately, the doc build requires files be fetched (see `tools/docupdate.py`).

The build should be altered to be self-contained for this particular case. In the meantime, we have no choice but to remove any option for a doc build in Gentoo.

**Comment by rogerbinns** [comment]
The correct thing for gentoo to do is actually use the releases, not the repository snapshots.  Look at [this release](https://github.com/rogerbinns/apsw/releases/tag/3.9.2-r1).  Although there are two links at the bottom labelled "Source code", they are actually just a snapshot of the repository at that tag.  There is a hyperlink at the top labelled "Source" which is the actual source release.  It downloads "apsw-3.9.2-r1.zip" which is the actual release.  If you look in that file you see there is a doc subdirectory, so the only tool needed for doc is ```cp -r```.

I have repeatedly asked github to stop adding these "Source code" files to releases that aren't actually helpful to anyone, but they won't.  The repository is in a maintainer state, as most are.  docupdate for example is part of the repository, but not part of the release as it is a maintainer tool.  If you insist on building from the repository and not the release, then you will not be able to build the documentation.  It links to sqlite's pages all over the place, and the page to link to is based on on a database downloaded from the SQLite website at doc build time (they coalesce and split pages for various APIs and constants all the time, so fixed links won't work or be a maintenance burden). 

 BTW docupdate doesn't actually download anything - it just updates the source files for the doc so that they have the most recent version number in various places.  code2rst does actually do downloads for the linking mentioned in the previous paragraph.

BTW2 grabbing the "archive" links as you do also means you aren't doing [pgp verification of the code](http://rogerbinns.github.io/apsw/download.html#verifying-your-download).

**Comment by rogerbinns** [comment]
FWIW I have sent yet another email to github asking them to stop with the incorrect misleading "Source code" links.  They have always refused before.
