### ISSUE TITLE
The documentation lacks to say there is no `executescript`

### ISSUE THREAD

**Issue by Hibou57** [rogerbinns/apsw#204]
The page [DBAPI notes](http://rogerbinns.github.io/apsw/dbapi.html), does not mention there is no `executescript` with APSW.

Side note: APSW is 13 times faster than standard Python sqlite3 module, for me!

**Comment by rogerbinns** [comment]
Glad to hear about the speed.

There is no executescript in DBAPI - search the page https://www.python.org/dev/peps/pep-0249/

executescript is a pysqlite thing because it can't handle more than one statement in an execution string.  And then it ignores statements within that return results.

In other words, every method in APSW starting with "execute" accepts multiple statements, and does return values.  There is no need for anything like executescript.
