### ISSUE TITLE
Fetch SQLite is broken due to year change

### ISSUE THREAD

**Issue by darkfeline** [rogerbinns/apsw#226]
```
$ python setup.py fetch --sqlite
/home/ubuntu/virtualenvs/venv-3.6.0/lib/python3.6/site-packages/setuptools/dist.py:331: UserWarning: Normalizing '3.15.2-r1' to '3.15.2.post1'
  normalized_version,
running fetch
  Getting download page to work out current SQLite version
    Fetching https://sqlite.org/download.html
    Version is 3.16.2
  Getting the SQLite amalgamation
    Fetching https://sqlite.org/2016/sqlite-autoconf-3160200.tar.gz
       Error  HTTP Error 404: Not Found
        Try # 2
       Error  HTTP Error 404: Not Found
        Try # 3
       Error  HTTP Error 404: Not Found
        Try # 4
       Error  HTTP Error 404: Not Found
        Try # 5
       Error  HTTP Error 404: Not Found
error: HTTP Error 404: Not Found
```

The new path is https://sqlite.org/2017/sqlite-autoconf-3160200.tar.gz

**Comment by rogerbinns** [comment]
This has already been fixed in the code, but has not been deployed in a release yet.  (There have been a few 3.16.x releases while I waited for it to quiet down.)  The release will likely happen in the next few days.

If you need it to work right now, then apply this change to the code:  https://github.com/rogerbinns/apsw/commit/af7269d5eb9bf5300b6dd9437697962b0849932c#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by karelv** [comment]
I have had exactly the same error message, but with 2018 => 2019 year change.
