### ISSUE TITLE
Portable installation

### ISSUE THREAD

**Issue by dunha** [rogerbinns/apsw#245]
Hi
I am stuck on a corporate system without admin rights and so unable to install or update the sqlite dll in the current python installation
I have WinPython as well and would like to try apsw with it. Is there any way to install apsw binaries to WinPython?
I have tried pip but ran into trouble not having the build tools installed

**Comment by rogerbinns** [comment]
Building Python stuff on Windows is extremely difficult due to the build tools which is why I provide the binaries.  The apsw builds include SQLite inside and do not use any other on the system.

apsw itself is just a single file.  To get a pre-built Windows one, go to the [downloads](https://github.com/rogerbinns/apsw/releases) and download the relevant .exe.  Rename the extension to .zip and extract using your favourite unzipper.  You'll find an apsw.pyd inside (name varies by python version).  You can put that with your code and `import apsw` will find it.

**Comment by dunha** [comment]
Like magic. Thanks
