### ISSUE TITLE
Integrating APSW shell into the dbcli framework

### ISSUE THREAD

**Issue by thorstenkampe** [rogerbinns/apsw#246]
Would you consider integrating APSW shell into the `dbcli` framework (https://github.com/dbcli)? There are already excellent command line clients for PostgreSQL, MySQL and recently Microsoft SQL Server.

**Comment by thorstenkampe** [comment]
Background for the specific approach of `dbcli`: https://www.youtube.com/watch?v=hJhZhLg3obk

**Comment by E3V3A** [comment]
@thorstenkampe  
I don't see why you would want to do this, since sqlite3 is already acting like it's own shell, and interacting great with whatever shell environment you already are using, ie. Bash, Cmd etc.

**Comment by thorstenkampe** [comment]
@E3V3A it would be better a better command line experience. For the same reason that APSW has it's own implementation of sqlite shell (https://github.com/dbcli/litecli). But it's already been done: https://github.com/dbcli/litecli

**Comment by rogerbinns** [comment]
I did briefly look into this, and it is far too much work.  I am prepared to refactor some of the shell code to make this easier for someone else to do, but will not do it myself.  In any event it is probably better that dbcli integrate with the standard (py)sqlite module instead of APSW since pysqlite does all the DBAPI semantics etc and has far wider compatibility.

The purpose of the APSW shell was compatibility with the SQlLite one, but also to then allow it to be extended from Python etc.
