### ISSUE TITLE
Add support for auxiliary columns in r-tree tables (sqlite 3.24.0)

### ISSUE THREAD

**Issue by zilman** [rogerbinns/apsw#250]
Hi,

Sqlite [released 3.24](https://sqlite.org/changes.html).

Beginning with SQLite version 3.24.0 (2018-06-04), r-tree tables can have auxiliary columns that store arbitrary data. Auxiliary columns are marked with a "+" symbol before the column name. 

This is now valid syntax:

```
 CREATE VIRTUAL TABLE demo_index2 USING rtree(
     id,              -- Integer primary key
     minX, maxX,      -- Minimum and maximum X coordinate
     minY, maxY,      -- Minimum and maximum Y coordinate
     +objname TEXT,   -- name of the object
     +objtype TEXT,   -- object type
     +boundary BLOB   -- detailed boundary of object
  );
```

This is a very cool future, you should support it.

> SQLError: SQLError: near "+": syntax error

**Comment by kmedcalf** [comment]
This is an SQLite3 SQL language feature that does not require any particular support from APSW, just the use of an SQLite3 version that supports the feature.  (That is, it appears to work perfectly fine for me -- the fact you get an "SQLError" indicates that the problem is that the version of SQLite3 you are using is not up-to-date -- is not using the 3.24 version of SQLite3).  

The GEOPOLY virtual table and associated functions do not require any specific support either (though perhaps the ability to enable the GEOPOLY extension when compiling the amalgamation.

**Comment by rogerbinns** [comment]
Thanks for the correct diagnosis @kmedcalf
