### ISSUE TITLE
undefined symbol: sqlite3_set_last_insert_rowid when importing apsw

### ISSUE THREAD

**Issue by bencaine1** [rogerbinns/apsw#255]
I'm getting an error when I try to import the latest release of apsw. Any ideas? Thanks!

```
# sqlite3 --version
3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238b4f9
# pip install git+https://github.com/rogerbinns/apsw.git@3.25.2-r1
# pip show apsw | grep Version
Version: 3.25.2.post1
# python
>>> import apsw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/apsw.so: undefined symbol: sqlite3_set_last_insert_rowid
```

**Comment by rogerbinns** [comment]
You are dynamically linking apsw against an older version of the sqlite library.  That older version does not have sqlite3_set_last_insert_rowid hence the load error.  The sqlite3 command gives the version of the shell, not the version of the sqlite library.

The [documentation](https://rogerbinns.github.io/apsw/download.html?highlight=pip#i-really-want-to-use-pip) includes how to use pip and get the sqlite library compiled into apsw, so that the system version has no effect.

**Comment by bencaine1** [comment]
Thank you!
