### ISSUE TITLE
sqlite3_preupdate_hook

### ISSUE THREAD

**Issue by adontz** [rogerbinns/apsw#260]
Is there any chance to get sqlite3_preupdate_hook support?

**Comment by rogerbinns** [comment]
That is going to be quite a bit of effort, for something that is compiled out of SQLite by default.  No promises and it will likely be quite a while.

**Comment by adontz** [comment]
Not sure I understood you. How is SQLITE_ENABLE_PREUPDATE_HOOK different from SQLITE_ENABLE_FTS5?

**Comment by rogerbinns** [comment]
* PREUPDATE_HOOK is not enabled by default in SQLite builds so far fewer people use it

* Just enabling the define as is the case with FTS5 won't do anything useful since it makes 4 C functions available which you need to use for the hook to have effect

* [Those 4 functions](https://www.sqlite.org/c3ref/preupdate_count.html) then need code added to APSW to interface between C and Python

* ... and a a whole bunch of test code 

* ... and documentation

**Comment by adontz** [comment]
Will you accept a pull request?

**Comment by rogerbinns** [comment]
Only if it is complete - ie includes all the code, all the testing and all the documentation.
