### ISSUE TITLE
Include database file name in exception message

### ISSUE THREAD

**Issue by diekhans** [rogerbinns/apsw#263]
APSW exceptions don't include the database file name, making it more difficult to understand why an error occured.  For instance:

`apsw.CantOpenError: CantOpenError: unable to open database file`

**Comment by rogerbinns** [comment]
SQLite generates the message and it is considerably more complicated than it first appears.

The good news is that [SQLite diagnostics](https://rogerbinns.github.io/apsw/tips.html#diagnostics) will tell you exactly what is going on.

**Comment by diekhans** [comment]
I have looked at the sqlite code and it is rather drastic change at that level.

However, it _looks_ most straight-forward to append the database name in apsw.
I say "looks", because I don't really know the python C API and am most likely completely wrong.

If you consider it doable in APSW, I would code it with some guidance.

Anyway, thanks for the pointer on SQLite diagnostics, while not as convenient as an obvious message, it would be a good thing to add into to debug logging.

**Comment by rogerbinns** [comment]
I am not adding it to APSW because it is not as helpful as first seems.  Names are relative to cwd with SQLite's own logic used to generate an absolute pathname.  Various options complicate things (eg urls).  The failure to open is far more likely to be caused by issues with the directory, wal/journal etc.

ie even if it told you the filename in your case, the most likely thing you'd need next is the actual full pathname and the reason why.  Due to the VFS structure of SQLite, that comes through the diagnostics mechanism.
