### ISSUE TITLE
apsw-3.27.2-r1-sigs.zip not found

### ISSUE THREAD

**Issue by leung-d** [rogerbinns/apsw#267]
I click on this link in the Download page ... I get "Not found" ... thanks

**Comment by rogerbinns** [comment]
Thank you for spotting this - it was all my fault.  I applaud you for actually checking signatures.  The root cause was following the release procedure by memory instead of the documented checklist, that then resulted in this omission.

Version 3.28.0 was pushed today, and I followed the document so all is good now.
