### ISSUE TITLE
Multiple aggregate conditions return no results

### ISSUE THREAD

**Issue by altunyurt** [rogerbinns/apsw#286]
I have a table with this following schema 
```SQL
CREATE TABLE IF NOT EXISTS "price_history" (
    "id" INTEGER NOT NULL PRIMARY KEY,
    "product_id" INTEGER NOT NULL,
    "price" DECIMAL(10, 2) NOT NULL,
    "date" DATE NOT NULL,
    "change" Decimal(10, 2)  NULL,
FOREIGN KEY ("product_id") REFERENCES "product" ("id"));
CREATE INDEX "pricehistory_product_id" ON "price_history" ("product_id");
```

I'm running this following code with apsw v3.31.1-r1 on python v3.7.1, sqlite3 v3.22 to get a list of items: 
```python3
SQL = """SELECT "t1"."id",
       "t1"."product_id",
       "t1"."price",
       "t1"."change",
       "t1"."date"
FROM "price_history" AS "t1"
GROUP BY "t1"."product_id"
HAVING ((count("t1"."id") > 1)
        AND ("t1"."change" < "0"))"""

conn = apsw.Connection("db/database.db", flags=apsw.SQLITE_OPEN_READONLY)
cur = conn.cursor()
cur.execute(SQL).fetchall()
```
It returns empty list.

The same query with sqlite3 driver and the sqlite3 cli on database returns the list of items. 

Removing ```AND ("t1"."change" < "0")``` condition, the query returns appropriate list of items.

**Comment by rogerbinns** [comment]
I can't reproduce this without data too.  In any event APSW does not alter how SQLite processes SQL.

This sort of thing usually happens due to using different SQLite versions.  All it takes is a different sqlite library being used than you expected.  You can use ````.version```` in the SQLite cli and [this sequence in apsw](https://github.com/rogerbinns/apsw/blob/master/tests.py#L18).
