### ISSUE TITLE
 'apsw.Connection' object has no attribute 'rollback'

### ISSUE THREAD

**Issue by alpha2beta** [rogerbinns/apsw#295]
Recently I am update my scripts from the sqlite3 wrapper to apsw.

Everything is fine except df.to_sql() function.

It gives the 'apsw.Connection' object has no attribute 'rollback'

May I ask what could be the solution to overcome or pass this issue?

Kind regards

**Comment by rogerbinns** [comment]
cursor.execute("ROLLBACK")

rollback is a [dbapi method](https://www.python.org/dev/peps/pep-0249/#id4) because some databases do things at an API level (not SQL level).

I recommend you take the [transaction approach](https://rogerbinns.github.io/apsw/tips.html#transactions) using the with statement.  Less code to write and rollback/commit happen automatically.
