### ISSUE TITLE
Installation fails on Linux - 404 on amalgamation file

### ISSUE THREAD

**Issue by 2-5** [rogerbinns/apsw#306]
Amalgamation download fails, because it looks in the /2020/ directory, while the file was apparently moved to the /2021/ directory

https://sqlite.org/2020/sqlite-autoconf-3340100.tar.gz (fails)
https://sqlite.org/2021/sqlite-autoconf-3340100.tar.gz (works)

```
(venv3) python3.8 setup.py fetch --missing-checksum-ok --all build --enable-all-extensions
.../venv3/lib/python3.8/site-packages/setuptools/dist.py:461: UserWarning: Normalizing '3.34.0-r1' to '3.34.0.post1'
  warnings.warn(tmpl.format(**locals()))
running fetch
  Getting download page to work out current SQLite version
    Fetching https://sqlite.org/download.html
    Version is 3.34.1
  Getting the SQLite amalgamation
    Fetching https://sqlite.org/2020/sqlite-autoconf-3340100.tar.gz
       Error  HTTP Error 404: Not Found
        Try # 2
       Error  HTTP Error 404: Not Found
        Try # 3
       Error  HTTP Error 404: Not Found
        Try # 4
       Error  HTTP Error 404: Not Found
        Try # 5
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
        Try # 6
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
        Try # 7
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
        Try # 8
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
        Try # 9
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
        Try # 10
        [Python has https issues? - using http instead]
       Error  HTTP Error 404: Not Found
error: HTTP Error 404: Not Found
```

**Comment by rogerbinns** [comment]
Yes they put the release year as part of the url path, but when the switchover happens isn't known in advance, so I have to wait till each January to update the code.  The code in git is updated.  However I haven't done a release since SQLite 3.35 will be coming out soon.

Your choices are:

* Add ````--version=3.34.0```` to the fetch bit which gets last years last release
* Copy the current [setup.py from git](https://github.com/rogerbinns/apsw/blob/master/setup.py) and run again
* Make a case for a release being done now, and then wait a few days for it to happen

Thanks for using apsw and reporting the issue
