### ISSUE TITLE
Recovering PyPi name

### ISSUE THREAD

**Issue by polyrand** [rogerbinns/apsw#309]
Hi! A few days ago I was reading about a Python ML library that had a (somewhat) similar problem with PyPi to the one APSW has. It turns out there's a PEP ([PEP 541](https://www.python.org/dev/peps/pep-0541/)) that lets you claim ownership of a PyPi package.

[Here](https://github.com/pypa/pypi-support/issues/651)'s the issue where the maintainers of that ML library are trying to do it.

When I read it, I immediately thought of APSW. I wanted to share it in case it's something you hadn't considered. I've read the docs where it says that, even having control over the PyPi name wouldn't make the installation 100% reliable, but still, I think having a PyPi package with some sensible defaults would be better than nothing.

Thanks for the awesome work in the library!

**Comment by rogerbinns** [comment]
The easy part has always been having the package in pypi.  The extremely difficult part is what that should do.  In all this time (apsw has been around since 2004) I have been unable to figure out what "sensible defaults" would be.  For example should it:

* use whatever SQLite is on the system
* the current version of SQLite when apsw is uploaded to pypi
* the current version of SQLite when someone uses apsw from pypi

Whichever one is picked will be wrong for a non-trivial number of people.  That would be ok if there was a way to easily override the choice.  For example if pip extras worked then these could be expressed as apsw[system], apsw, and apsw[latest], There is also the question of what extensions to enable, although enabling all by default is probably okay.

I'll make you a deal: if you can figure out a reasonable way to override defaults for people using pypi, I'll add the package there.

**Comment by polyrand** [comment]
One way I think it could work is directly offering different packages. The same way that there's pysqlite3/pysqlite3-binary and psycopg2/psycopg2-binary (I know the purpose of those is different).

I'm not very familiar with wrapping/compiling stuff with a Python package, but I think it could be reasonable to have something like: apsw / apsw-latest. The first one uses the system sqlite, with whatever extensions it comes with, the other one uses the current latest version.

Regarding the latest version, I guess it would be easier to wrap the latest version when uploading to PyPi, just in case some sqlite3 APIs change for whatever reason and break the current implementation (I'm talking from ignorance here).

**Comment by rogerbinns** [comment]
Doing at least 3 different packages is considerably more work, and requires a lot of development and testing.  In any event no one has yet come up with an approach that would work and enough information to implement it.  I'll keep waiting.
