### ISSUE TITLE
install apsw with pypy3

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [rogerbinns/apsw#323]
I am not able to install apsw with pypy3. Can this support be added?

I suppose pypy3 will run an apsw python script faster than vanilla python? If so, it is beneficial to support pypy3 by apsw?

**Comment by rogerbinns** [comment]
Note that APSW is C code that bridges the C based API of CPython with the C based API of SQLite.  pypy focuses on Python code, and provides some compatibility code for C extensions.  I did quickly try again and pypy3 doesn't implement [PyUnicode_CopyCharacters](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_CopyCharacters) which was added to CPython 10 years ago.  It is extra work to reimplement that sort of thing, and may eventually happen.

But if you are using apsw, you'll find that the vast majority of time is spent in SQLite itself, especially doing things like waiting for storage to confirm data is really written and can survive a power failure.  ie if you want to run things faster, your best effort would be in optimising the SQL side and paying very careful attention to transaction boundaries since that is where SQLite has to wait on storage.

I am busy updating APSW and will try pypy again when done.
