### ISSUE TITLE
Support for asyncio implementation of Virtual Tables

### ISSUE THREAD

**Issue by cancan101** [rogerbinns/apsw#325]
Taking a look at the [Virtual Tables](https://rogerbinns.github.io/apsw/vtable.html) it would be cool if the methods could be asyncio compatible such that e.g. `Next` is non blocking (awaitable).

This would ideally allow downstream users to await the results of a cursor call and eventually use apsw for an [asyncio-compatible SQLALchemy dialect](https://github.com/sqlalchemy/sqlalchemy/discussions/7854).

Related library with a ticket for asyncio: https://github.com/plasticityai/supersqlite/issues/2

It seems like the db API interface could be made async followings approach in https://github.com/omnilib/aiosqlite but that doesn't solve the allowing the virtual table functions themselves to use non blocking calls.

**Comment by rogerbinns** [comment]
I can't see any way of doing this, but if you can figure it out I'll try.

The problem is that SQLite is C code and can't return to the event loop.  The aiosqlite approach is to do the synchronous stuff in a separate worker thread leaving the main thread async.  To call async virtual tables would require blocking the main thread and letting a helper thread run the async code and event loop.

Have you tried something like https://github.com/miyakogi/syncer to wrap your async code into a sync interface?

**Comment by cancan101** [comment]
Totally understandable not adding knowledge of event loops to apsw.

For reference I took a look at the [sqlite3 bindings for npm](https://github.com/mapbox/node-sqlite3) (listed as "Asynchronous, non-blocking [SQLite3](https://sqlite.org/) bindings for [Node.js](http://nodejs.org/).") and it looks like the node api (n-api) offers some primitives in C/C++ to work with the event loop such as [`napi_queue_async_work`](https://nodejs.org/api/n-api.html#napi_queue_async_work) + `napi_create_async_work` which used e.g. [here](https://github.com/mapbox/node-sqlite3/blob/593c9d498be2510d286349134537e3bf89401c4a/src/database.cc#L559-L565). I am less familiar with what, if anything, Python provides to (easily) interface with the event loop.

**Comment by rogerbinns** [comment]
Javascript only has a single thread so async is essential.  Also note that they only expose the query interface of SQLite - APSW provides that with cursors as iterators in the same manner.
