### ISSUE TITLE
Stub .pyi file invalid location

### ISSUE THREAD

**Issue by dfateyev** [rogerbinns/apsw#327]
The .pyi stub file is installed to an invalid location: to the system prefix catalog (e.g. "/usr") instead of "python sitearch".
```
error: Installed (but unpackaged) file(s) found:
   /usr/apsw.pyi
```
As a workaround, the file can be moved to the proper location by hands — but better to fix this behavior.

It looks like maintainers are trying to follow https://peps.python.org/pep-0484 rather than the later https://peps.python.org/pep-0561/. However, the way they are installing the stub file with data_files in setup.py is resulting in it getting dumped in %_prefix.

**Comment by rogerbinns** [comment]
I'm "the maintainers" :)  I did indeed follow pep 484 since pep 561 doesn't give anything specific (other than a magic filename) that I could figure out.  (And that magic filename is not referenced anywhere when running sdist or doing an install.)

In any event things do go to the right place on --user and Windows installs which is a good start.  I've been unable to find how to have the stub file in sitearch.  Patches welcome!

**Comment by dfateyev** [comment]
Unfortunately I cannot fix it shortly since I cannot get all the setup process peculiarities. It takes time to figure all the details out.
I'm sticking to a workaround with moving resulting file as for now.

**Comment by rogerbinns** [comment]
I'm hoping someone can figure this out, because I can't figure out the right answer!

This is a really ugly corner of Python.  The most straightforward thing would be putting the annotations directly on the classes and methods as regular Python code does.  However they prevent that for stuff written in C for undisclosed reasons. Then:

* There are 3 different syntaxes for the type annotations (same as Python, a magic docstring header that can't include return information and has stuff like $self, and the type stub syntax)
* There are 3 different deployment mechanisms for type stubs: two different PEPs and submitting to typeshed.

**Comment by mgorny** [comment]
Ah, sorry, I now see that the `.pyi` file is sufficient for pydoc to work, so that part of my comment was incorrect. Still, I don't think that there's a clean of installing the file top-level.

**Comment by rogerbinns** [comment]
@mgorny a .py wrapper around a private ````_apsw```` .so/.dll would indeed work, and its contents would actually be the [type stub file](https://github.com/rogerbinns/apsw/blob/master/apsw.pyi) but with each ````...```` redirecting to the corresponding ````_apsw```` function/data.

But then what is the point of type stubs since they  wouldn't be needed in this scenario? And it would break things since classes/types would end up being members of ````_apsw```` not ````apsw```` which is bound to confuse other code.  The code in the .so/.dll would also have to be aware of the split namespaces (eg where to find ````connection_hooks````).

Doing this would be a last resort, and rather ugly!  Hopefully someone can figure out a reasonable solution.

**Comment by mgorny** [comment]
#337 is the best I was able to come up with.

**Comment by rogerbinns** [comment]
The approach worked and shipped in 3.38.5-r1

**Comment by dfateyev** [comment]
@rogerbinns I have noticed that the directory structure was changed in the latest release:

For 3.38.1-r1:
```
$ tree site-packages
site-packages
├── apsw-3.38.1.post1-py3.10.egg-info
│   ├── dependency_links.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   └── top_level.txt
└── apsw.cpython-310-x86_64-linux-gnu.so

1 directory, 5 files
```

For 3.38.5-r1:
```
$ tree site-packages
site-packages
├── apsw
│   ├── __init__.cpython-310-x86_64-linux-gnu.so
│   ├── __init__.pyi
│   └── py.typed
└── apsw-3.38.5.post1-py3.10.egg-info
    ├── dependency_links.txt
    ├── PKG-INFO
    ├── SOURCES.txt
    └── top_level.txt

2 directories, 7 files
```
Could you confirm, is it the expected change with all filenames correct? Should I package the whole `apsw` directory with its content as-is?

**Comment by rogerbinns** [comment]
Yes the layout is correct and intended.  The .so is the code, the .pyi are the type stubs, and py.typed is because of PEP0561.
