### ISSUE TITLE
Better xBestIndex handling

### ISSUE THREAD

**Issue by cancan101** [rogerbinns/apsw#332]
[Supporting the `IN` constraints in `xBestIndex` is somewhat more complicated](https://www.sqlite.org/c3ref/vtab_in.html) than other operators (since it takes a sequence of values on the RHS) and requires access to a few sqlite functions:
- [`sqlite3_vtab_in`](https://www.sqlite.org/c3ref/vtab_in.html)
- [`sqlite3_vtab_in_first`](https://www.sqlite.org/c3ref/vtab_in_first.html)
- [`sqlite3_vtab_in_next`](https://www.sqlite.org/c3ref/vtab_in_first.html)

**Comment by rogerbinns** [comment]
The approach I am thinking of using is:

* a parameter for create_module that indicates enhanced xBestIndex support
* the enhanced xBestIndex is passed an object with many methods & attributes on it

The object would contain both the input best index information, as well as the result information.  That is also how functions like sqlite3_vtab_in would be callable.  It would also be somewhat future proof with more methods and attributes added in the future as SQLite evolves.

**Comment by rogerbinns** [comment]
Also incorporate #329, #278, #180, #188,  #189, #190, #130,

**Comment by rogerbinns** [comment]
git master now has an IndexInfo object which represents [sqlite3_index_info](https://www.sqlite.org/c3ref/index_info.html) and associated methods.  A flag to createmodule says whether to use traditional BestIndex or BestIndexObject taking this.  Feedback appreciated.  sqlite3_vtab_in isn't wrapped yet because it requires passing state between two calls.  (You still get Filter called for each in member.)

This is a paste of the current doc:

class IndexInfo

IndexInfo represents the [sqlite3_index_info](https://www.sqlite.org/c3ref/index_info.html) used in the [VTTable.BestIndexObject()](https://github.com/rogerbinns/apsw/issues/332#apsw.VTTable.BestIndexObject) method.

Naming is identical to the C structure rather than Pythonic. You can access members directly while needing to use get/set methods for array members.

You will get [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) if you use the object outside of an BestIndex method.

[apsw.ext.index_info_to_dict()](https://github.com/rogerbinns/apsw/issues/ext.html#apsw.ext.index_info_to_dict) provides a convenient representation of this object as a [dict](https://docs.python.org/3/library/stdtypes.html#dict).

IndexInfo.colUsed: [set](https://docs.python.org/3/library/stdtypes.html#set)[[int](https://docs.python.org/3/library/functions.html#int)]
(Read-only) Columns used by the statement. Note that a set is returned, not the underlying integer.

IndexInfo.distinct: [int](https://docs.python.org/3/library/functions.html#int)
(Read-only) How the query planner would like output ordered

Calls: [sqlite3_vtab_distinct](https://sqlite.org/c3ref/vtab_distinct.html)

IndexInfo.estimatedCost: [float](https://docs.python.org/3/library/functions.html#float)
Estimated cost of using this index

IndexInfo.get_aConstraintUsage_argvIndex(which: [int](https://docs.python.org/3/library/functions.html#int)) → [int](https://docs.python.org/3/library/functions.html#int)
Returns argvIndex for aConstraintUsage[which]

IndexInfo.get_aConstraintUsage_omit(which: [int](https://docs.python.org/3/library/functions.html#int)) → [bool](https://docs.python.org/3/library/functions.html#bool)
Returns omit for aConstraintUsage[which]

IndexInfo.get_aConstraint_collation(which: [int](https://docs.python.org/3/library/functions.html#int)) → [str](https://docs.python.org/3/library/stdtypes.html#str)
Returns collation name for aConstraint[which]

Calls: [sqlite3_vtab_collation](https://sqlite.org/c3ref/vtab_collation.html)

IndexInfo.get_aConstraint_iColumn(which: [int](https://docs.python.org/3/library/functions.html#int)) → [int](https://docs.python.org/3/library/functions.html#int)
Returns iColumn for aConstraint[which]

IndexInfo.get_aConstraint_op(which: [int](https://docs.python.org/3/library/functions.html#int)) → [int](https://docs.python.org/3/library/functions.html#int)
Returns op for aConstraint[which]

IndexInfo.get_aConstraint_rhs(which: [int](https://docs.python.org/3/library/functions.html#int)) → [SQLiteValue](https://github.com/rogerbinns/apsw/issues/apsw.html#apsw.SQLiteValue)
Returns right hand side value if known, else None.

Calls: [sqlite3_vtab_rhs_value](https://sqlite.org/c3ref/vtab_rhs_value.html)

IndexInfo.get_aConstraint_usable(which: [int](https://docs.python.org/3/library/functions.html#int)) → [bool](https://docs.python.org/3/library/functions.html#bool)
Returns usable for aConstraint[which]

IndexInfo.get_aOrderBy_desc(which: [int](https://docs.python.org/3/library/functions.html#int)) → [bool](https://docs.python.org/3/library/functions.html#bool)
Returns desc for aOrderBy[which]

IndexInfo.get_aOrderBy_iColumn(which: [int](https://docs.python.org/3/library/functions.html#int)) → [int](https://docs.python.org/3/library/functions.html#int)
Returns iColumn for aOrderBy[which]

IndexInfo.idxFlags: [int](https://docs.python.org/3/library/functions.html#int)
Mask of [SQLITE_INDEX_SCAN flags](https://github.com/rogerbinns/apsw/issues/apsw.html#apsw.mapping_virtual_table_scan_flags)

IndexInfo.idxNum: [int](https://docs.python.org/3/library/functions.html#int)
Number used to identify the index

IndexInfo.idxStr: Optional[[str](https://docs.python.org/3/library/stdtypes.html#str)]
Name used to identify the index

IndexInfo.nConstraint: [int](https://docs.python.org/3/library/functions.html#int)
(Read-only) Number of constraint entries

IndexInfo.nOrderBy: [int](https://docs.python.org/3/library/functions.html#int)
(Read-only) Number of order by entries

IndexInfo.orderByConsumed: [bool](https://docs.python.org/3/library/functions.html#bool)
True if index output is already ordered

IndexInfo.set_aConstraintUsage_argvIndex(which: [int](https://docs.python.org/3/library/functions.html#int), argvIndex: [int](https://docs.python.org/3/library/functions.html#int)) → [None](https://docs.python.org/3/library/constants.html#None)
Sets argvIndex for aConstraintUsage[which]

IndexInfo.set_aConstraintUsage_omit(which: [int](https://docs.python.org/3/library/functions.html#int), omit: [bool](https://docs.python.org/3/library/functions.html#bool)) → [None](https://docs.python.org/3/library/constants.html#None)
Sets omit for aConstraintUsage[which]

**Comment by cancan101** [comment]
Are you still doing the index remapping of the current method?:
>Note The implementation of this method differs slightly from the [SQLite documentation](https://sqlite.org/vtab.html) for the C API. You are not passed “unusable” constraints. The argv/constraintarg positions are not off by one. In the C api, you have to return position 1 to get something passed to [VTCursor.Filter()](https://rogerbinns.github.io/apsw/vtable.html#apsw.VTCursor.Filter) in position 0. With the APSW implementation, you return position 0 to get Filter arg 0, position 1 to get Filter arg 1 etc.

`set_aConstraintUsage_omit` is that for the "double checking flag" ie the the optional boolean on the current method's return?

**Comment by rogerbinns** [comment]
When using IndexInfo the underlying [sqlite3_index_info](https://www.sqlite.org/c3ref/index_info.html) is presented exactly as is - there is no remapping of argument numbers, no filtering out of unusable constraints etc.

````set_aConstraintUsage_omit```` refers to the ````omit```` field in ````aConstraintUsage```` and does control if SQLite double checks.  It isn't optional in the sense that SQLite presets it to ````False````.
