### ISSUE TITLE
Unable to compile APSW 3.38.5-r1 and SQLITE3 3.38.5 on MacOS

### ISSUE THREAD

**Issue by kwloafman** [rogerbinns/apsw#339]
I'm getting `#error Your SQLite version is too old.  It must be at least 3.38` even when both versions match.  Plus I'm getting 7 errors, not warnings.

I've attached the log file of the compile run.

[apsw.log](https://github.com/rogerbinns/apsw/files/8871013/apsw.log)

**Comment by rogerbinns** [comment]
No problem - I was coming up with an explanation/solutions:

short:  use pip install and everything will work

longer:  use sdist (without fetch) to generate source, and then use fetch in the build_ext step

explanation:

There was a long forgotten "feature" where doing fetch and sdist in the same command line would bundle the SQLite source code into the APSW sdist.  That was removed for this release.

The reason is that configure was run to get compilation flags for SQLite.  As an example, this is important because if HAVE_USLEEP is not defined then the minimum busy wait is 1 second, whereas with usleep it is microseconds.  The SQLite amalgamation and the flags would be bundled.  But those flags are only appropriate for the system configure was run on.  In order to get the correct flags on another system, configure would have to be run again, but that requires the full source SQLite distribution.  So the bundling could cause problems (wrong flags) and fetch is needed again anyway to run configure properly.  Hence the removal.  Apologies for catching you out on this, but hopefully being in pypi can make things simpler.

**Comment by kwloafman** [comment]
Actually, I needed to increase DSQLITE_MAX_ATTACHED to 125 (max) which is a compile step, otherwise I would have used it out-of-the-box.  

Thanks for hard work!

**Comment by rogerbinns** [comment]
I just looked through the SQLite code and the max attached appears to only have one side effect.  When less than 30 then a bitfield keeps track of connections in an int, while more than than that requires multiple ints and slightly more complicated macros.  So it costs an extra 3 ints having the highest limit.

How about I change the APSW default compilation to make this the maximum anyway?  Far less annoying than needing 11 attached databases needing a recompile!

**Comment by kwloafman** [comment]
That sounds good to me.  Then I'd just have to check that the user had installed the correct version and not used the ancient one from the repo.  

How would you distribute it?  Pip?

**Comment by rogerbinns** [comment]
That commit has your answer :-)  It affects all builds done using the amalgamation, which includes PyPI.  The extra 12 bytes of memory consumed is fine.  Also note that you can find out what the limit is with:

    db.limit(apsw.SQLITE_LIMIT_ATTACHED, -1)
