### ISSUE TITLE
Fail to install on Termux or with Pyinstaller

### ISSUE THREAD

**Issue by eliranwong** [rogerbinns/apsw#365]
On Termux, when I run "pip3 install apsw", I got the following error.

![signal-2022-09-13-095003](https://user-images.githubusercontent.com/25262722/189860774-3397659e-984f-4445-be1d-08565cda2461.png)

Then, I downloaded the source, and run "pip3 install .", I got the following error.

![signal-2022-09-13-095009](https://user-images.githubusercontent.com/25262722/189860751-d6066d39-acbb-40b0-9211-45905edf1501.png)

In addition, I have a project to be packaged with pyinstaller, I got errors to include apsw whereas other dependencies work as expected.

**Comment by rogerbinns** [comment]
APSW is C code gluing together the C API of SQLite and the C API of Python.  Consequently a compiler and linker are needed.

You need to install the termux package `binutils` to get a linker.  The command is `pkg install binutils`.  Then your first pip install command will work.

The first pip command is failing because SQLite's `configure` script can't find a linker.  The first command downloads the corresponding SQLite version.  The second command is failing because it is using your existing SQLite library which is too old a version.

APSW works fine with pyinstaller and I've shipped products on multiple platforms with it.  You'll need to include more information about failures if they aren't covered by installing `binutils`.  Please re-open this issue if things still do not work for you, and thank you for reporting the issue.
