### ISSUE TITLE
Consider to adapt tests to support ZipVFS

### ISSUE THREAD

**Issue by mikir** [rogerbinns/apsw#394]
Although [ZipVFS](https://www.sqlite.org/zipvfs/doc/trunk/www/index.wiki) extension is licensed, please consider to support this extension in APSW tests. It might be usefull for some users.

The changes which solve all ZipVFS problems in tests can be found on [my](https://github.com/mikir/apsw/commit/2682098e209c40914106a9637da4e5b9b6299cf7) fork.

If it helps, I can check after each release if ZipVFS is still supported and provide corresponded patch in tests if needed.

**Comment by rogerbinns** [comment]
I'm unclear on what it is you are trying to test.  If you have ZipVFS does it become the default?  The documentation doesn't imply that is the case.

Note that the APSW test suite is to check that APSW code works correctly - it does not verify SQLite works correctly, although that happens somewhat as a side effect.  The reason tests are run in journal and then in WAL mode is to catch any behavioural differences, since it wasn't known when WAL was introduced if there would be any.  The last section where most of your changes are all about writing your own VFS.  ZipVFS should have no effect unless it is the default.

Can you run this in the environment where you have ZipVFS enabled:

     python3 -c "import apsw; print(apsw.vfsnames())"

**Comment by mikir** [comment]
Thank you for such quick feedback!

Yes, it is default. I forgot to mention it.

Command `apsw.vfsnames()` gives the following results:

```
['zipvfs', 'cksmvfs', 'zipvfsonly', 'multiplex', 'unix', '_zipvfsonly', '_zipvfs', '_multiplex', 'memdb', 'unix-excl', 'unix-dotfile', 'unix-none']
```

**Comment by rogerbinns** [comment]
Here is my plan:

* Add an APSW API so that a VFS can be unregistered by name
* Change test start so that it unregisters:  ````'zipvfs', 'cksmvfs', 'zipvfsonly', 'multiplex',````
* That should then leave "unix", "win32" etc as the default and all tests should work fine.

Sound good?

An easier approach would be to hardcode the per platform native vfs name (eg "unix" or "win32") but I really don't want to maintain a table like that and it feels more fragile and less future proof.

**Comment by mikir** [comment]
This sounds really good. Then, we would be able to unregister problematic VFS before testing and not to patch tests anymore.

I agree that hardcoding the native vfs names is fragile and bad for maintainance.

**Comment by rogerbinns** [comment]
@mikir I believe this is now done correctly.  Please can you test?  You can either checkout master branch, or use **test** pypi https://test.pypi.org/project/apsw/

**Comment by mikir** [comment]
Sure, I will test it ASAP. Thanks a lot so far! I will write as soon as tests are done.

**Comment by mikir** [comment]
I am sorry for a short delay. I have tested it. It works here succesfully if I moved

```
        for name in ('zipvfs', 'cksmvfs', 'zipvfsonly', 'multiplex'):
            if name in apsw.vfsnames():
                apsw.unregister_vfs(name)
```

from the `setup()` to `setUp()` method. Probably there are more `apsw` instances. Does it make sense?

**Comment by rogerbinns** [comment]
How did it fail when in ````setup````?  

````setup```` is called once during the test suite and does things like delete tests that aren't applicable etc.  ````setUp```` is called before every test function - well over 100 times!  ````apsw```` is the module itself and there is only one of those - testing does not unload and reload the module.

**Comment by mikir** [comment]
This was segfault.

I see, `apsw` is only one. OK, I will evaluate it more deeply to have more info and come back again.

**Comment by mikir** [comment]
So, the problem is calling `apsw.shutdown()` in tests. For example in `testConfig`, before `apsw.shutdown`, we have correct VFS names:

```
['unix', '_zipvfsonly', '_zipvfs', '_multiplex', 'memdb', 'unix-excl', 'unix-dotfile', 'unix-none']
```

After `apsw.shutdown`, we have again original set of VFS names:

```
['zipvfs', 'cksmvfs', 'zipvfsonly', 'multiplex', 'unix', '_zipvfsonly', '_zipvfs', '_multiplex', 'memdb', 'unix-excl', 'unix-dotfile', 'unix-none']
```

And there are several tests which calls `apsw.shutdown`.

To unregister ZipVFS in `setUp()` works but it is not optimal as you pointed out. It might be better to introduce some new private method for APSW shutdown which unregister ZipVFS as well. And each test which calls APSW shutdown will call this private method. However, this approach could be error prone if somebody will write new test and forget about it and will call APSW shutdown directly...

**Comment by rogerbinns** [comment]
Thank you for figuring out the root  cause.  This also confirms shutdown works :)  I am moving the unregistering to ````setUp```` because that is most robust.

**Comment by mikir** [comment]
OK. Thanks a lot for perfect cooperation!. :-)
