### ISSUE TITLE
Unable to attach memdb from non-memdb vfs

### ISSUE THREAD

**Issue by hoehrmann** [rogerbinns/apsw#414]
Using apsw-3.41.0.0:

```
>>> db = apsw.Connection('file:/dfa?vfs=memdb', vfs='memdb')
>>> db2 = apsw.Connection(':memory:')
>>> db2.execute("attach database 'file:/dfa?vfs=memdb' as d");
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cursor.c", line 240, in resetcursor
apsw.CantOpenError: CantOpenError: unable to open database: file:/dfa?vfs=memdb
>>> db.execute("attach database 'file:/dfa?vfs=memdb' as d");
<apsw.Cursor object at 0x7f36786b2480>
```

```
 ❯  sqlite3 :memory:
SQLite version 3.41.0 2023-02-21 18:09:37
Enter ".help" for usage hints.
sqlite> attach database 'file:/dfa?vfs=memdb' as d;
sqlite> create table d.t(id int);
sqlite> .schema
CREATE TABLE d.t(id int);
```

**Comment by rogerbinns** [comment]
You got bitten by the SQLite shell having more extensions and options turned on than the SQLite library (which APSW wraps).  Specifically [SQLITE_CONFIG_URI](https://sqlite.org/c3ref/c_config_covering_index_scan.html#:~:text=must%20be%20threadsafe.-,SQLITE_CONFIG_URI,-The%20SQLITE_CONFIG_URI%20option) is off by default in the library, but turned on in the SQLite shell.  You need to turn it on:

    apsw.config(apsw.SQLITE_CONFIG_URI, True)

I figured it out by turning on [SQLite logging](https://rogerbinns.github.io/apsw/tips.html#diagnostics) where it was apparent that the full string was being treated as the filename (ie including the `file:` and `?vfs=` bits).

**Comment by hoehrmann** [comment]
I think you mean `apsw.config(apsw.SQLITE_CONFIG_URI)`, without the `True` argument. Thanks, this seems better. Would be nice if the documentation noted that.

**Comment by rogerbinns** [comment]
I did mean what I wrote.  It is a boolean setting - you can turn the setting on or off.  The APSW code also enforces that.

The SQLite doc is somewhat confusing, but if you look at the top of [the doc](https://sqlite.org/c3ref/c_config_covering_index_scan.html) you will see that it gives the parameters taken in comments.

The SQLite code is like this where you will note it is taking an int from the varargs passed in.

```C
    case SQLITE_CONFIG_URI: {
      /* EVIDENCE-OF: R-25451-61125 The SQLITE_CONFIG_URI option takes a single
      ** argument of type int. If non-zero, then URI handling is globally
      ** enabled. If the parameter is zero, then URI handling is globally
      ** disabled. */
      sqlite3GlobalConfig.bOpenUri = va_arg(ap, int);
      break;
    }
```

**Comment by rogerbinns** [comment]
I did just check the SQLite shell code and this is the only setting that is changed from the library default.  It does also do SQLITE_CONFIG_MULTITHREAD which doesn't take a value, and makes the library thread **unsafe**!  However the shell is single threaded so that is fine.

There are 15 extensions that are used too.

**Comment by hoehrmann** [comment]
```
 ❯  python3 
Python 3.11.2 (main, Feb  7 2023, 13:52:42) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apsw
>>> apsw.config(apsw.SQLITE_CONFIG_URI, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes exactly 1 argument (2 given)
>>> db = apsw.Connection(':memory:')
>>> db.config(apsw.SQLITE_CONFIG_URI, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown config operation 17
>>> 
```

**Comment by rogerbinns** [comment]
Apologies for this.  Handling of SQLITE_CONFIG_URI was fixed in https://github.com/rogerbinns/apsw/commit/c45c308499e4622c8e37bb21ac0a9d5079edb051 but hasn't been merged into master yet which is why it worked for me.

I had forgotten about the correct solution to this which is to use [SQLITE_OPEN_URI](https://sqlite.org/c3ref/c_open_autoproxy.html) in the flags to [opening a connection](https://rogerbinns.github.io/apsw/connection.html#apsw.Connection).  This is preferred over changing the global configuration of the SQLite library.

For the second part you are the second person to be bitten by it this year.  apsw.config calls [sqlite3_config](https://sqlite.org/c3ref/config.html) which configures the SQLite library as a whole.  Connection.config calls [sqlite3_db_config](https://sqlite.org/c3ref/db_config.html) which configures a specific connection.  They use different constant names, but the integer values overlap.  I have been thinking about making the constants derive from [enum](https://docs.python.org/3/library/enum.html) which would make it possible to detect the wrong names have been used.  But the calls also wouldn't behave as expected anyway.
