### ISSUE TITLE
Make dynamic linking to SQLite easier

### ISSUE THREAD

**Issue by hoehrmann** [rogerbinns/apsw#426]
I have recently written an SQLite profilier https://github.com/federlieb/federprof that I would like to use in combination with apsw. The profiler uses LD_PRELOAD and thus requires that applications link dynamically against SQLite. I have managed to link apsw against a pre-compiled SQLite library, but not without patching setup.py (it always would at least attempt to download the amalgamtion, which I have taken as sign that it would link statically against that; that behavior is also how I read the apsw documentation; and there does not seem to be code in setup.py to build a shared library from the SQLite sources). It would be nice if there was better documentation on how to link against a (non-system) dynamic SQLite library, and if there was a simple way to build apsw as it would normally do, but so that it would create a dynamic library for SQLite and link against it.

**Comment by rogerbinns** [comment]
If you download the source or binary from pypi then you get the same thing - APSW with SQLite of the corresponding version embedded statically and all extensions enabled.  This is intentional with the discussion at #310.

You have two ways of avoiding that - no need to modify `setup.py`:

1. Delete the `setup.cfg` from the pypi downloaded source.  This is what is causing the automatic SQLite download.
2. Use the source from [a release](https://github.com/rogerbinns/apsw/releases/tag/3.41.2.0) which doesn't have the `setup.cfg`.

APSW will not build SQLite as a shared library and similar because there are too many configurations.  [This is the code](https://github.com/rogerbinns/apsw/blob/master/setup.py#L141) used to extract options from a SQLite shared library.

Be aware that you will need to [match APSW and SQLite options](https://rogerbinns.github.io/apsw/build.html#matching-apsw-and-sqlite-options).  

The documentation [should be cleaned up](https://github.com/rogerbinns/apsw/issues/427).
