### ISSUE TITLE
connection.set_row_trace - excepts; Connection.setrowtrace works

### ISSUE THREAD

**Issue by mohmad-null** [rogerbinns/apsw#515]
`connection.set_row_trace` raises `AttributeError: 'apsw.Connection' object has no attribute 'set_row_trace'` despite using 3.43.0.

`Connection.setrowtrace` works fine but doesn't seem to be documented (I'm assuming as it's deprecated https://rogerbinns.github.io/apsw/changes.html#index-51) in the connection API - https://rogerbinns.github.io/apsw/connection.html

**Comment by rogerbinns** [comment]
The name changing happened in version 3.43.2.0 - currently in the changelog at this position https://rogerbinns.github.io/apsw/changes.html#id7

**Comment by mohmad-null** [comment]
Oh, because in the logs (above link) it's under 3.0.8-r1 and the text implies they're available. But yes, I see it's *also* under 3.43.2.

**Comment by rogerbinns** [comment]
3.0.8 came out 20 years ago!  The changed names section is appended to the the changes page since that seemed the most logical place, and my hope was that virtually no one would ever need to see it because all the doc covers the pep 8 compliant names.

You unfortunately got caught out by using an old version of apsw with the newest version of the docs :-)  Is there as reason you aren't using an up to date version of apsw?
