### ISSUE TITLE
Avoid superfluous readonly warnings

### ISSUE THREAD

**Issue by DavidBuchanan314** [rogerbinns/apsw#544]
My application involves frequent short-lived read-only database connections, and I use the default "best practices" config. Everything works fine, but my logs get a little clogged up with:

```
WARNING:root:SQLITE_LOG: statement aborts at 25: [pragma "optimize"(65538)] attempt to write a readonly database (8) SQLITE_READONLY
```

I believe it happens due to this logic:

https://github.com/rogerbinns/apsw/blob/418bd0e33754bafd5515bfb0521801e7f77c4d3b/apsw/bestpractice.py#L77-L80

I like having the warning logging on by default, and I don't want to turn it off. I also like having the `pragma optimize` on (for my writeable connections, at least).

My first thought was that you could check `Connection.readonly()` rather than try/catch, but it's non-obvious what `name` argument should be passed, so it wouldn't work correctly in all cases (it would work fine for me, though).

Perhaps there could be a context manager to temporarily suppress specific types of warning/error logging? (this would be broadly useful, there are other "expected" warnings generated elsewhere in my codebase)

**Comment by rogerbinns** [comment]
Thanks for reporting this.  The commit includes a test and a fix.  The connection hooks are run when the `main` database is opened so that was the `Connection.readonly()` parameter.  try/catch can't be used because the log messages come from inside SQLite whereas try/catch can only work with explicit error codes.  The fix will be in the next APSW release.

I too get annoyed at nuisance SQLite messages, like when it reprepares statements.

Sadly there is no context manager for suppressing logging.  unittest has some [nice stuff](https://docs.python.org/3/library/unittest.html#:~:text=the%20following%20methods%3A-,Method,New%20in,-assertRaises\(exc%2C)  to check logging does or doesn't happen, and there is [contextlib.suppress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress) to suppress exceptions, redirect stdout/err etc.  You are pretty much stuck with [logging filters](https://docs.python.org/3/library/logging.html#filter-objects).

**Comment by DavidBuchanan314** [comment]
Thank you for the fix, and thank you for apsw, it provides exactly the level of abstraction over sqlite that I was looking for.
