### ISSUE TITLE
Also provide source release as tar.gz

### ISSUE THREAD

**Issue by mgorny** [rogerbinns/apsw#548]
Commit 8ded9d28770b3366914b64eb42f23c870461d01c has forced GitHub archives to be empty. We were using these "useless" archives to package apsw for Gentoo, as they were the only tarballs that provided the complete source code. Please revert this change, as it serves no real purpose, and is outright harmful to others.

**Comment by rogerbinns** [comment]
The source code is provided for each release as apsw-VERSION.zip for example for [3.47.2.0](https://github.com/rogerbinns/apsw/releases/tag/3.47.2.0) it is the top most link labelled [Source](https://github.com/rogerbinns/apsw/releases/download/3.47.2.0/apsw-3.47.2.0.zip).

github automatically adds a repository snapshot they annoyingly label "Source code" hence the change.

Could you please clarify how the repository snapshot is what you need, and not the project official source release?

There is advice for packagers like yourself [in the docs](https://rogerbinns.github.io/apsw/install.html#advice-for-packagers).

Looking at your [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/apsw/apsw-3.47.1.0.ebuild) the `src_configure` should write to `setup.apsw` and should **not** have the `enable=load_extension` line since that will be automatically determined by getting the system SQLite config.

The official source release is the code necessary to build and run the project.  It does not include maintainer tools etc.  It also includes the HTML documentation which the `use_doc` line of the ebuild is looking form.  (The repository snapshot has some of the doc in rst format and more of it is extracted using maintainer tools from C source comments.)  I extensively and only test the source release is correct and complete, and builds the project correctly.

**Comment by mgorny** [comment]
We don't want to use `.zip` since that format is inefficient and requires non-standard tooling (only `tar` is provided by default). Could you provide a `.tar.xz` or equivalent archive then?

**Comment by rogerbinns** [comment]
Yes I can provide a tar.gz (most compatible compression).  It will have exactly the same structure and contents as the zip - eg a top level directory like `apsw-3.47.2.0`.

**Comment by mgorny** [comment]
Thank you.

**Comment by rogerbinns** [comment]
The .tar.gz will be available in the next release which should be [mid January](https://sqlite.org/forum/forumpost/4f4d06a9f6)

**Comment by mgorny** [comment]
> Looking at your [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/apsw/apsw-3.47.1.0.ebuild) the `src_configure` should write to `setup.apsw` and should **not** have the `enable=load_extension` line since that will be automatically determined by getting the system SQLite config.

We have readded it because of https://bugs.gentoo.org/851741 (just checked the history to make sure). Perhaps the underlying issue was fixed since.

**Comment by rogerbinns** [comment]
I can't reproduce that.  With use_system_sqlite_config where extension loading is enabled (your case) I see 

````
running build_ext
Extracting configuration from libsqlite3.so.0
SQLite: Using system sqlite include/libraries
SQLite: Using generated /space/apsw/sqlite3/sqlite3config.h

$ grep EXTENSION sqlite3/sqlite3config.h 
#undef  SQLITE_ENABLE_LOAD_EXTENSION
#define SQLITE_ENABLE_LOAD_EXTENSION 1
````

The apsw code does [#ifndef SQLITE_OMIT_LOAD_EXTENSION](https://github.com/rogerbinns/apsw/blob/master/src/connection.c#L2395) because extension loading is enabled by default.

Looking in sqlite3.c compiling with SQLITE_OMIT_LOAD_EXTENSION does generate OMIT_LOAD_EXTENSION in the [compilation options](https://www.sqlite.org/c3ref/compileoption_get.html) which is the API used for use_system_sqlite_config.  sqlite3.c also uses `#ifndef SQLITE_OMIT_LOAD_EXTENSION` to decide if extension loading should be omitted, so the apsw code does match.

It looks like the [sqlite ebuild hardcodes extension loading on](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-db/sqlite/sqlite-3.47.2.ebuild#n155) anyway.  So it looks to me that the setting in the apsw ebuild is turning on something that is already on, #defining it to the value it already has (you'll see `-DSQLITE_ENABLE_LOAD_EXTENSION=1` on the compiler invocation line).   It doesn't look there is a use flag to turn extension loading off, although static linking may be able to do that.

I am intending to [wrap the session extension](https://github.com/rogerbinns/apsw/issues/543) soon which is also C apis that may be absent depending on SQLite build flags.  It looks like the sqlite always enables session, but it would be nice to get things right.

I appreciate your help getting to the bottom of this.

**Comment by gador** [comment]
This worked until 3.47.1.0 and stopped working starting at 3.47.2.0. Could you please, re-add the github archives?

**Comment by rogerbinns** [comment]
@gador I'm confused.  This was first implemented for 3.**48**.0.0 release of January 14 2025.

[Every release](https://github.com/rogerbinns/apsw/releases) since then, including the latest 3.**49**.2.0 has the same assets.  You can see the asset count is 6, which includes the two fake "Source code" github  creates, and then the `.tar.gz` and .`zip` of the APSW release, and their corresponding `.cosign-bundle` signatures.

If you are specifically talking about the "Source code" that github adds, they are not the source code.   They were a snapshot of the repository at the corresponding tag.  They should not be used for APSW, and I was able to cause them to be zero length to at least highlight this.   You can read more about that [here](https://github.com/orgs/community/discussions/6003) and [here](https://github.com/orgs/community/discussions/158761).

You should be using the project provided zip or tar.gz after checking the cosign bundle.

**Comment by gador** [comment]
@rogerbinns I see. This has been a missunderstanding on my part, then. I maintain your package for NixOS and we usually fetch the Github source directly. This has the benefit of using a specilized fetcher and this has been working quite well (e.g. see https://github.com/NixOS/nixpkgs/blob/292fa7d4f6519c074f0a50394dbbe69859bb6043/pkgs/development/python-modules/apsw/default.nix#L19-L24). 

I disagree about most of your points made in the discussion and see more benefits in distributing the source _as is_ (especially for developers) but this is your project and I'm not going to argue. 
Thanks for taking your time explaining your motivation and I switched to fetching your `tar.gz` archives for NixOS

**Comment by eli-schwartz** [comment]
I find it fairly surprising that NixOS should have a "specialized fetcher" for GitHub autogenerated releases but not one for GitHub Releases Artifacts.

**Comment by rogerbinns** [comment]
@gador thanks for packaging APSW for NixOS!

APSW like many other projects has the repository in a "project maintenance" configuration.  Build steps are taken to produce release artifacts.  The problem is github making an archive of the git, calling it "Source code", and implying you can build from that.  That it worked so far with APSW is an accident, and not a configuration that is tested or even correct!  That is why I and others in the github discussions have a problem with the "Source code" artifacts.  I would be delighted to understand your thoughts on this.

I do have some comments and queries about the [apsw nix recipe](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/apsw/default.nix)

The documentation has [Advice for packagers](https://rogerbinns.github.io/apsw/install.html#advice-for-packagers) which covers using standard Python project build instructions.  

It also shows using a `setup.apsw` to automatically detect which APIs are present in the environment provided SQLite which is important for FTS5 and Session support (both enabled by [default in Nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/sqlite/default.nix)).  Although it says "system SQLite", it really picks up whichever SQLite is available when doing `ctypes.cdll.LoadLibrary("sqlite3")` so that should work for Nix.

Testing should be done by running `python -m apsw.tests`.   It looks like Nix is using pytest, but if that works it is an accident.  The test files and directory layout have also changed for the next release.

Why are various tests disabled?  The extension loading one does spit out a message about the *optional* test extension not being built and hence not being tested.   The others are important tests, and do run on all the platforms.  It makes no sense for them to be disabled.

**Comment by gador** [comment]
> I find it fairly surprising that NixOS should have a "specialized fetcher" for GitHub autogenerated releases but not one for GitHub Releases Artifacts.

I believe this to be a nicer way around fetching commits from a git repository. I think the idea behind this is to build from a certain commit, usually referenced by a tag.
Maybe one could expand the GitHub fetcher to also look for GitHub release artifacts but currently it's just a fancier way around fetchGit.

**Comment by gador** [comment]
> APSW like many other projects has the repository in a "project maintenance" configuration.  Build steps are taken to produce release artifacts.  The problem is github making an archive of the git, calling it "Source code", and implying you can build from that.  That it worked so far with APSW is an accident, and not a configuration that is tested or even correct!  That is why I and others in the github discussions have a problem with the "Source code" artifacts.  I would be delighted to understand your thoughts on this.

I find this very interesting. What's the major difference between the git source tree at a release tag and a published source artifact?


> 
> I do have some comments and queries about the [apsw nix recipe](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/apsw/default.nix)
> 
> The documentation has [Advice for packagers](https://rogerbinns.github.io/apsw/install.html#advice-for-packagers) which covers using standard Python project build instructions.  
> 
> It also shows using a `setup.apsw` to automatically detect which APIs are present in the environment provided SQLite which is important for FTS5 and Session support (both enabled by [default in Nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/sqlite/default.nix)).  Although it says "system SQLite", it really picks up whichever SQLite is available when doing `ctypes.cdll.LoadLibrary("sqlite3")` so that should work for Nix.
> 

Yes, it does. In fact this is why my update PR doesn't update to the newest version but to 3.48.0.0

> Testing should be done by running `python -m apsw.tests`.   It looks like Nix is using pytest, but if that works it is an accident.  The test files and directory layout have also changed for the next release.

Oh ok, I'll have a look at it👍
Yes, Nixpkgs uses pytest by default. This standardizes the way we handle disabled tests etc.
I'll look into the benefit of changing it to apsw.tests
> 
> Why are various tests disabled?  The extension loading one does spit out a message about the *optional* test extension not being built and hence not being tested.   The others are important tests, and do run on all the platforms.  It makes no sense for them to be disabled.

Thanks for the feedback! I'll have to look into it, but am on mobile right now..

**Comment by eli-schwartz** [comment]
> > I find it fairly surprising that NixOS should have a "specialized fetcher" for GitHub autogenerated releases but not one for GitHub Releases Artifacts.
> 
> I believe this to be a nicer way around fetching commits from a git repository. I think the idea behind this is to build from a certain commit, usually referenced by a tag. Maybe one could expand the GitHub fetcher to also look for GitHub release artifacts but currently it's just a fancier way around fetchGit.

Well I mean. You can believe whatever you want.

I am just wondering why:
- NixOS has a helper to aid in constructing the correct URL for an automatically generated GitHub archive
- this helper is so important for aiding in DRY and reducing the maintenance burden of NixOS that you feel it's a better tradeoff to use this helper function and NOT use canonical downloads
- nobody has created a helper to fetch canonical downloads so that you can simultaneously reduce the maintenance burden of NixOS while also respecting the upstream canonical downloads

It seems a little backwards to me?

**Comment by eli-schwartz** [comment]
> Oh ok, I'll have a look at it👍 Yes, Nixpkgs uses pytest by default. This standardizes the way we handle disabled tests etc. I'll look into the benefit of changing it to apsw.tests

One of the downsides of using pytest everywhere, to me, is that it increases the transitive closure of a package. This is important in Gentoo, because packages are frequently built from source, so keeping the closure size down is important for reproducibility and bootstrapping.

That means, if it's possible to run the test suite for a package using only builtin functionality, we might prefer to do so rather than use large, bulky tools with giant transitive closures purely for visual sugar, or even for uniformity in argument passing. Both are trivial and not really worth the closure size.

I know this is less important for distributions such as Arch Linux and NixOS, but still, it's something to think about.

**Comment by gador** [comment]
> > > I find it fairly surprising that NixOS should have a "specialized fetcher" for GitHub autogenerated releases but not one for GitHub Releases Artifacts.
> > 
> > I believe this to be a nicer way around fetching commits from a git repository. I think the idea behind this is to build from a certain commit, usually referenced by a tag. Maybe one could expand the GitHub fetcher to also look for GitHub release artifacts but currently it's just a fancier way around fetchGit.
> 
> Well I mean. You can believe whatever you want.

Thanks.. I guess?
> 
> I am just wondering why:
> - NixOS has a helper to aid in constructing the correct URL for an automatically generated GitHub archive
> - this helper is so important for aiding in DRY and reducing the maintenance burden of NixOS that you feel it's a better tradeoff to use this helper function and NOT use canonical downloads
> - nobody has created a helper to fetch canonical downloads so that you can simultaneously reduce the maintenance burden of NixOS while also respecting the upstream canonical downloads

Most of the open source projects I have worked with actually build fine with the git source snapshot at a release tag and don't depend on some differences added to the source code download. In nixpkgs we have an automated way of updating projects which work with the GitHub helper but not as well with a pure fetchUrl helper.

IMHO a project should build fine with the pure source code and not some added build steps to build the source code. This seems IMHO a bit over-the-top?

> 
> It seems a little backwards to me?

Well, you can think what you want ;-)

But in all honesty, I think there are multiple ways of doing things and we have to work with all kinds of upstream differences and build systems.
Working with the pure source from a source tree helps debugging. I'm just thinking of all the extra steps and reading one would have to do to debug a build issue if we  first have to figure out how the "second" Source Code is being generated.

**Comment by eli-schwartz** [comment]
> Most of the open source projects I have worked with actually build fine with the git source snapshot at a release tag and don't depend on some differences added to the source code download. In nixpkgs we have an automated way of updating projects which work with the GitHub helper but not as well with a pure fetchUrl helper.
> 
> IMHO a project should build fine with the pure source code and not some added build steps to build the source code. This seems IMHO a bit over-the-top?

There is a vast, vast world of software built with GNU Autotools, all of which intrinsically depends on some differences added to the source code download.

It's possible to reproduce those differences, but differences they surely are.

(Reproducing those differences adds quite a bit to the transitive closure by the way. This is a big problem for bootstrappable builds.)

For the python ecosystem specifically, it's strongly recommended to use a PyPI sdist as that always includes differences added to the source code (in the form of PKG-INFO, which some packages critically depend on (and the only other alternative is building from an actual `git clone`, which is challenging to checksum and adds an even larger transitive closure). This needs to be balanced against the fact that many projects explicitly delete the test suite from their sdists, which means we do need to use GitHub automatically generated archives, and then figure out how to correctly reproduce the sdist creation process including hacking up "automatic tagging from git" processes.

> But in all honesty, I think there are multiple ways of doing things and we have to work with all kinds of upstream differences and build systems.

Sure, and this project's way is to provide explicit release tarballs. :)

> Working with the pure source from a source tree helps debugging. I'm just thinking of all the extra steps and reading one would have to do to debug a build issue if we first have to figure out how the "second" Source Code is being generated.

I've rarely had such an issue before when packaging. Actually I think the only times this has been an issue are always for software that has been abandoned and unmaintained for at least 5 years.

Seriously. It's invariably stuff like "include pregenerated documentation such as manpages or HTML docs", or else "pregenerated C files that the build system will recreate if you rm -f them", or "recording the package version based on git exports", or "GNU configure scripts".

The really tough one is always the GNU configure scripts. Abandoned software often doesn't correctly `autoreconf -fi` with any known version of the Autotools, so using "the pure source from a source tree" (I assume you mean a git tree, not a source tree) is the precise opposite of helpful because you *can't do it*. And giving up and using the existing copy of the "second" Source Code will work fine (or at least work at all).

**Comment by eli-schwartz** [comment]
> Testing should be done by running `python -m apsw.tests`. It looks like Nix is using pytest, but if that works it is an accident. The test files and directory layout have also changed for the next release.
> 
> Why are various tests disabled? The extension loading one does spit out a message about the _optional_ test extension not being built and hence not being tested. The others are important tests, and do run on all the platforms. It makes no sense for them to be disabled.

@rogerbinns I went ahead and played around with the difference between pytest and the canonical test command.

If for example loadextension is disabled in the build config, pytest fails with several tests that the canonical test command makes sure to skip. That happens because pytest collects all the tests from apsw/tests.py but doesn't run `if __name__ == '__main__':` logic

So that's probably why NixOS had to hack around disabling tests, because the tests weren't correctly being skipped for them and they had to guess at which tests were important to disable and manually do it.

It is even worse after refactoring tests.py into `tests/__main__.py` :) because pytest does not want to load that file at all. And if you force it, it throws an error saying:
```
imported module '__main__' has this __file__ attribute:
  /usr/lib/python3.13/site-packages/pytest/__main__.py
which is not the same as the test file we want to collect:
  /home/eschwartz/git/apsw/apsw/tests/__main__.py
```

I think this makes for fairly good proof that you are correct, and one should NOT try to inject pytest, as it doesn't work, not even by accident.

**Comment by rogerbinns** [comment]
At some point in the past the Python community decided that adding extra commands to setup.py was deprecated in favour of stiuff in pyproject.toml which is probably why a maintainer decided to stop doing tests via a setup.py command.  As you've discovered using `python -m apsw.tests` is the only way to do it, what the project does, and what the github actions builds for pypi do.    (The setup.py test command still works however because I don't break things.)

Under the hood the tests are using the standard library unittest module.

As you've guessed, the difference between APSW git clone and source release is around generated files.  Generated files depend on external packages (eg sphinx and rtd_theme for documentation), external databases (SQLite toc for documentation, a recipes database for the FTS5 example code), and external data files (code and test generation from a bunch of Unicode data files).  The documentation and type stubs are generated from other files in the repository.

Currently APSW only requires setuptools to build (declared in pyproject.toml), and no other Internet access.  This is because some of the generated files are checked into git, which is why you got lucky with a git build.  However this will change going forward as I want fewer generated files in git, but still maintain the "no Internet access" rule.

The github source release I provide specifically has the following combined today:

* python sdist
* Generated HTML documentation with google analytics turned off
* Fonts removed from generated HTML (read the docs theme adds them)
* Command line interface man page (apsw.1) generated with docutils

**Comment by gador** [comment]
> > Most of the open source projects I have worked with actually build fine with the git source snapshot at a release tag and don't depend on some differences added to the source code download. In nixpkgs we have an automated way of updating projects which work with the GitHub helper but not as well with a pure fetchUrl helper.
> > IMHO a project should build fine with the pure source code and not some added build steps to build the source code. This seems IMHO a bit over-the-top?
> 
> There is a vast, vast world of software built with GNU Autotools, all of which intrinsically depends on some differences added to the source code download.
> 
> It's possible to reproduce those differences, but differences they surely are.
> 
> (Reproducing those differences adds quite a bit to the transitive closure by the way. This is a big problem for bootstrappable builds.)

I'm indeed not too familiar with autotools and autoreconf so I can't say too much about it. It still baffles me that autotools depends on (as you call it) `differences` that the developer has to add to its Source Code and that it would be too difficult to reproduce them from the git snapshot.

> 
> For the python ecosystem specifically, it's strongly recommended to use a PyPI sdist as that always includes differences added to the source code (in the form of PKG-INFO,) which some packages critically depend on (and the only other alternative is building from an actual `git clone`, which is challenging to checksum and adds an even larger transitive closure). 

Why would it be difficult to calculate a checksum from `git clone`? Git itself is build around a content-addressed hash, so this should actually make it _easier_.

>This needs to be balanced against the fact that many projects explicitly delete the test suite from their sdists, which means we do need to use GitHub automatically generated archives, and then figure out how to correctly reproduce the sdist creation process including hacking up "automatic tagging from git" processes.
> 
> > But in all honesty, I think there are multiple ways of doing things and we have to work with all kinds of upstream differences and build systems.
> 
> Sure, and this project's way is to provide explicit release tarballs. :)

Sure. And just to reiterate: I am _not_ here to argue that point. I'm happy with any kind of source code ;-)

> 
> > Working with the pure source from a source tree helps debugging. I'm just thinking of all the extra steps and reading one would have to do to debug a build issue if we first have to figure out how the "second" Source Code is being generated.
> 
> I've rarely had such an issue before when packaging. Actually I think the only times this has been an issue are always for software that has been abandoned and unmaintained for at least 5 years.
> 
> Seriously. It's invariably stuff like "include pregenerated documentation such as manpages or HTML docs", or else "pregenerated C files that the build system will recreate if you rm -f them", or "recording the package version based on git exports", or "GNU configure scripts".
> 

Ok. 
"include pregenerated documentation such as manpages or HTML docs" -> Can just as easily be build by the package manager.
"pregenerated C files that the build system will recreate if you rm -f them" -> I can understand not wanting to polute the git source tree but it does make sense keeping them for the sake of reproducibility. 
"recording the package version based on git exports" -> Can also be imitated by e.g. a preBuild hook, but it would be even better if the taged git source tree just has the version noted correctly and doesn't need to be calculated. 
GNU configure scripts" -> See above

> The really tough one is always the GNU configure scripts. Abandoned software often doesn't correctly `autoreconf -fi` with any known version of the Autotools, so using "the pure source from a source tree" (I assume you mean a git tree, not a source tree) is the precise opposite of helpful because you _can't do it_. And giving up and using the existing copy of the "second" Source Code will work fine (or at least work at all).

And this really shouldn't be the case. Alone from a reproducible build point of view there shouldn't be any differences given the correct build tool versions. But, as I said, I'm not too familiar with autotools, don't use them myself and for projects in nix they usually tend to work without too much hassle.

About the closure size: 
I get it that other distros (e.g. Gentoo) handles them differently. For nix, the tests (and the whole pytest suite) does not end up in the final closure but is only needed (once) on the build system.

**Comment by gador** [comment]
> I think this makes for fairly good proof that you are correct, and one should NOT try to inject pytest, as it doesn't work, not even by accident.

Thanks for testing this!

**Comment by eli-schwartz** [comment]
> I'm indeed not too familiar with autotools and autoreconf so I can't say too much about it. It still baffles me that autotools depends on (as you call it) `differences` that the developer has to add to its Source Code and that it would be too difficult to reproduce them from the git snapshot.

As long as you can successfully run `autoreconf -fi` it's not a problem. But autotools has been around for decades. It predates the 21st century. It has changed API over the decades, so not all projects work with the latest version. And especially older projects tended to have more complex steps, often documented in a text file, that have to be run before running aclocal / autoconf / automake / autoheader.

And various projects need e.g. pkg-config to be installed to successfully autoreconf, because pkg-config installs an autoconf library (`*.m4`) which needs to be used in ./configure but autoconf is not good at detecting missing M4 libraries so it doesn't correctly error out. Many other projects also provide M4 libraries for autoconf.

> > For the python ecosystem specifically, it's strongly recommended to use a PyPI sdist as that always includes differences added to the source code (in the form of PKG-INFO,) which some packages critically depend on (and the only other alternative is building from an actual `git clone`, which is challenging to checksum and adds an even larger transitive closure).
> 
> Why would it be difficult to calculate a checksum from `git clone`? Git itself is build around a content-addressed hash, so this should actually make it _easier_.

It certainly isn't easier. Git's content addressed hash is sha1 based, which means it's useless to people that require sha256 or blake2. You have to actually produce your own unique hash over the full bytes of the source tree, which means you need to invest in tooling to do so.


> Ok. "include pregenerated documentation such as manpages or HTML docs" -> Can just as easily be build by the package manager.

Nope! Not if the documentation generator isn't portable to hppa and sparc and mips and alpha and loong and ....

Pandoc is the worst thing to befall documentation ecosystems.

> "pregenerated C files that the build system will recreate if you rm -f them" -> I can understand not wanting to polute the git source tree but it does make sense keeping them for the sake of reproducibility.

Yes. And again, this is stuff that reduces the transitive closure. I can understand someone wanting to vet them but depending on the generator tool it can be very valuable to preserve them.

For flex and bison this isn't a big deal, it's easy to recreate. But what about the generated sources which flex uses to build itself?

Also vala has the same problem. Its C files are generated by vala itself.

> "recording the package version based on git exports" -> Can also be imitated by e.g. a preBuild hook, but it would be even better if the taged git source tree just has the version noted correctly and doesn't need to be calculated.

I added a special feature to `git` so that people could do this automatically in `git archive`, you don't need to convince me. :)

Nonetheless, there are many projects whose build systems literally run `git describe` unless they discover their unique, custom format of secondary sources, such as e.g. the Python `PKG-INFO` file.

> GNU configure scripts" -> See above

I did see above, yes. ;)

> > The really tough one is always the GNU configure scripts. Abandoned software often doesn't correctly `autoreconf -fi` with any known version of the Autotools, so using "the pure source from a source tree" (I assume you mean a git tree, not a source tree) is the precise opposite of helpful because you _can't do it_. And giving up and using the existing copy of the "second" Source Code will work fine (or at least work at all).
> 
> And this really shouldn't be the case. Alone from a reproducible build point of view there shouldn't be any differences given the correct build tool versions. But, as I said, I'm not too familiar with autotools, don't use them myself and for projects in nix they usually tend to work without too much hassle.

The issue is often getting the correct tool version across over a quarter of a century of releases, a time span during which the API has been revised a few times requiring individual projects to port their configure.ac off of deprecated constructs which are slated for removal in a few years.

And the existence of third party M4 libraries for autoconf makes this harder since you also may need older versions of some other program as well. This is a very real problem when you operate on the scale of decades.

> About the closure size: I get it that other distros (e.g. Gentoo) handles them differently. For nix, the tests (and the whole pytest suite) does not end up in the final closure but is only needed (once) on the build system.

Build time dependencies are still dependencies even if you can remove them after the fact. So, build time closures affect people who build from source by:
- taking a lot of time to build and install, 
- inviting dependency cycles (how do you test the dependencies of pytest, which use pytest as their test suite!)
- preventing bootstrap (weekly autobuilds of the binary seed, which Gentoo calls a "stage3 tarball", porting to new architectures)

Certainly, after dealing with all this and successfully installing a package it is possible to uninstall build dependencies using `emerge -c --with-bdeps=n` to clean unneeded packages including packages that are only used by the build system / test suite. But that does not solve bootstrapping. It also gets undone when you next upgrade the package, as you need those dependencies again, which is why the default is *not* to uninstall them.

**Comment by eli-schwartz** [comment]
> I'm still thinking of the `xz` backdoor, which was partly only present in the [release tarballs.](https://www.openwall.com/lists/oss-security/2024/03/29/4)

I personally feel the best answer to this is documenting how release artifacts are created so that people can "reproducibly build the release artifacts", not just "reproducibly compile the release artifacts into a binary".

**Comment by rogerbinns** [comment]
I do have a [wiki page](https://github.com/rogerbinns/apsw/wiki/Release-Procedure) that covers how new releases are made.

The release artifact is `make source` to build, and `make release` to sign, near the end.

I don't accept external contributions which mitigates the `xz` attack a little.  I don't know of any defenses should I turn evil though!

**Comment by gador** [comment]
@eli-schwartz thank for very much for the in-depth perspective into build systems and especially autotools! You raise some very valid points.

**Comment by gador** [comment]
> I do have a [wiki page](https://github.com/rogerbinns/apsw/wiki/Release-Procedure) that covers how new releases are made.
> 
> The release artifact is `make source` to build, and `make release` to sign, near the end.
> 
> I don't accept external contributions which mitigates the `xz` attack a little. I don't know of any defenses should I turn evil though!

Thanks for the link. This does make it more transparent how the release is generated. I don't think there is a good way against a project lead turning evil. Especially for large open-source projects a small change, even in plain view in the source, can be hard to detect. 

On another note: I opened a PR to switch to your test suite
